CREATE DATABASE empresa;
USE empresa;

CREATE TABLE EMPREGADO (
    CODIGO_EMPREGADO DECIMAL(6),
    NOME VARCHAR(50),
    CODIGO_CARGO DECIMAL(5),
    ENDERECO VARCHAR(50),
    BAIRRO VARCHAR(20),
    CIDADE VARCHAR(20),
    CODIGO_CHEFE DECIMAL(6),
    UF CHAR(2),
    DATA_NASC DATE,
    SEXO CHAR(1),
    FILIACAO VARCHAR(60),
    SALARIO DECIMAL(10)
);
                       
CREATE TABLE CARGO (
    CODIGO_CARGO VARCHAR(30),
    DESCRICAO_CARGO VARCHAR(30),
    SALARIO_MIN NUMERIC(7), -- NUMERIC equivale a DECIMAL.
    SALARIO_MAX NUMERIC(8),
    NIVEL_GRADUACAO CHAR(1)
);

CREATE TABLE DEPENDENTE (
    CODIGO_EMPREGADO DECIMAL(6),
    NOME_DEPENDENTE VARCHAR(50),
    SEXO CHAR(1),
    DATA_NASC DATE,
    PARENTESCO VARCHAR(15)
);
             
CREATE TABLE DEPARTAMENTO (
    CODIGO_DEP DECIMAL(3),
    NOME_DEP VARCHAR(30),
    CODIGO_GERENTE DECIMAL(6),
    DATA_INICIO_GERENTE DATE,
    DATA_CRIACAO DATE
);
