/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.vianna.sistemaclube.view.cadastros.cadutils;

import br.edu.vianna.sistemaclube.dao.impl.AtividadeDAO;
import br.edu.vianna.sistemaclube.dao.impl.EventoDAO;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.AdministradorDAO;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.InstrutorDAO;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.MembroDAO;
import br.edu.vianna.sistemaclube.model.atividades.Atividade;
import br.edu.vianna.sistemaclube.view.cadastros.atividades.ViewDetalhesAtividades;
import br.edu.vianna.sistemaclube.view.cadastros.eventos.ViewDetalhesEventos;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesAdministradores;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesInstrutores;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesMembros;

import javax.swing.*;
import java.sql.SQLException;

/**
 * @author William
 */
public class ViewDeletarRegistro extends javax.swing.JDialog {

    /**
     * Creates new form ViewDeletarRegistro
     */
    public ViewDeletarRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ViewDeletarRegistro(ViewDetalhesAtividades viewDetalhesAtividades, boolean modal) {
        super(viewDetalhesAtividades, modal);
        initComponents();
    }

    public ViewDeletarRegistro(ViewDetalhesEventos viewDetalhesEventos, boolean modal) {
        super(viewDetalhesEventos, modal);
        initComponents();
    }

    public ViewDeletarRegistro(ViewDetalhesAdministradores viewDetalhesAdministradores, boolean modal) {
        super(viewDetalhesAdministradores, modal);
        initComponents();
    }

    public ViewDeletarRegistro(ViewDetalhesInstrutores viewDetalhesInstrutores, boolean modal) {
        super(viewDetalhesInstrutores, modal);
        initComponents();
    }

    public ViewDeletarRegistro(ViewDetalhesMembros viewDetalhesMembros, boolean modal) {
        super(viewDetalhesMembros, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecalho = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblIcone = new javax.swing.JLabel();
        pnlCorpo = new javax.swing.JPanel();
        lblQuestao = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();
        txtIdItemSelecionado = new javax.swing.JTextField();
        lblIdItemSelecionado = new javax.swing.JLabel();
        lblAviso2 = new javax.swing.JLabel();
        pnlRodape = new javax.swing.JPanel();
        btnDeletar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apagar registro da base de dados");
        setIconImage(null);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        pnlCabecalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCabecalho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCabecalho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCabecalho.setText("Deletar registro");
        pnlCabecalho.add(lblCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 8, 500, -1));

        lblIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24x24/Question.png"))); // NOI18N
        pnlCabecalho.add(lblIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 40, 30));

        pnlCorpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblQuestao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuestao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestao.setText("Tem certeza que deseja deletar este registro?");

        lblAviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAviso.setText("Uma vez que o registro for deletado");

        txtIdItemSelecionado.setEditable(false);
        txtIdItemSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdItemSelecionado.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        txtIdItemSelecionado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdItemSelecionado.setText("0");
        txtIdItemSelecionado.setRequestFocusEnabled(false);

        lblIdItemSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdItemSelecionado.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblIdItemSelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdItemSelecionado.setText("ID do item");

        lblAviso2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAviso2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        lblAviso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAviso2.setText(" A OPERAÇÃO NÃO PODERÁ SER DESFEITA!");

        javax.swing.GroupLayout pnlCorpoLayout = new javax.swing.GroupLayout(pnlCorpo);
        pnlCorpo.setLayout(pnlCorpoLayout);
        pnlCorpoLayout.setHorizontalGroup(
            pnlCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCorpoLayout.createSequentialGroup()
                .addGroup(pnlCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCorpoLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lblIdItemSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAviso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txtIdItemSelecionado, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlCorpoLayout.setVerticalGroup(
            pnlCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCorpoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblQuestao)
                .addGap(15, 15, 15)
                .addComponent(lblAviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso2)
                .addGap(18, 18, 18)
                .addComponent(lblIdItemSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdItemSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDeletar.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.error.focusedBorderColor"));
        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Delete.png"))); // NOI18N
        btnDeletar.setLabel("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int opcaoSelecionada = JOptionPane.showConfirmDialog(rootPane, "Clique em SIM para deletar permanentemente o registro.\n" +
                "Clique em NÃO para voltar à tela anterior.", "Confirmar operação", JOptionPane.YES_NO_OPTION);
        if (opcaoSelecionada == JOptionPane.YES_OPTION) {
            deletar();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        btnCancelar.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void deletar() {
        try {
            if (this.getParent() instanceof ViewDetalhesAtividades) {
                new AtividadeDAO().apagar(Integer.parseInt(txtIdItemSelecionado.getText()));
                exibeMensagemDeSucessoNaExclusao();
                this.dispose();
            }
            else if (this.getParent() instanceof ViewDetalhesEventos) {
                new EventoDAO().apagar(Integer.parseInt(txtIdItemSelecionado.getText()));
                exibeMensagemDeSucessoNaExclusao();
                this.dispose();
            } else if (this.getParent() instanceof ViewDetalhesAdministradores) {
                new AdministradorDAO().apagar(Integer.parseInt(txtIdItemSelecionado.getText()));
                exibeMensagemDeSucessoNaExclusao();
                this.dispose();
            } else if (this.getParent() instanceof ViewDetalhesInstrutores) {
                new InstrutorDAO().apagar(Integer.parseInt(txtIdItemSelecionado.getText()));
                exibeMensagemDeSucessoNaExclusao();
                this.dispose();
            } else if (this.getParent() instanceof ViewDetalhesMembros) {
                new MembroDAO().apagar(Integer.parseInt(txtIdItemSelecionado.getText()));
                exibeMensagemDeSucessoNaExclusao();
                this.dispose();
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível executar a operação.\nERRO: " + ex.getMessage(), "Ocorreu um erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exibeMensagemDeSucessoNaExclusao() {
        JOptionPane.showMessageDialog(rootPane, "Item excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeletarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeletarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeletarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeletarRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewDeletarRegistro dialog = new ViewDeletarRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblAviso2;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JLabel lblIdItemSelecionado;
    private javax.swing.JLabel lblQuestao;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlCorpo;
    private javax.swing.JPanel pnlRodape;
    private javax.swing.JTextField txtIdItemSelecionado;
    // End of variables declaration//GEN-END:variables
    public JTextField getTxtIdItemSelecionado() {
        return txtIdItemSelecionado;
    }
}
