/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.vianna.sistemaclube.view.visualizacao.rankings;

import br.edu.vianna.sistemaclube.dao.impl.AvaliacaoDAO;
import br.edu.vianna.sistemaclube.model.avaliacoes.Avaliacao;
import br.edu.vianna.sistemaclube.model.rankings.GeraRanking;
import br.edu.vianna.sistemaclube.model.rankings.Ranking;
import br.edu.vianna.sistemaclube.model.usuarios.Usuario;
import br.edu.vianna.sistemaclube.utils.datahora.FormataData;
import br.edu.vianna.sistemaclube.utils.login.Sessao;
import br.edu.vianna.sistemaclube.view.cadastros.atividades.ViewCadastroAtividades;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.List;

/**
 * @author William
 */
public class ViewRanking extends javax.swing.JDialog {

    /**
     * Creates new form ViewDetalhesAtividades
     */
    public ViewRanking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ViewRanking(ViewCadastroAtividades viewCadastroAtividades, boolean modal) {
        super(viewCadastroAtividades, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTopo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlControles = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        tabPanelBuscar = new javax.swing.JTabbedPane();
        pnlBuscarPorNome = new javax.swing.JPanel();
        txtBuscarPorNome = new javax.swing.JTextField();
        btnBuscarPorNome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRanking = new javax.swing.JTable();
        pnlMelhorColocados = new javax.swing.JTabbedPane();
        pnlMelhoresDoRanking = new javax.swing.JPanel();
        txtPontuacaoSegundoLugar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPrimeiro = new javax.swing.JLabel();
        lblSegundo = new javax.swing.JLabel();
        lblTerceiro = new javax.swing.JLabel();
        lblPrimeiroLugar = new javax.swing.JLabel();
        lblSegundoLugar = new javax.swing.JLabel();
        lblTerceiroLugar = new javax.swing.JLabel();
        lblPontuacaoPrimeiroLugar = new javax.swing.JLabel();
        lblPontuacaoTerceiroLugar = new javax.swing.JLabel();
        lblPontuacaoSegundoLugar = new javax.swing.JLabel();
        txtPontuacaoTerceiroLugar = new javax.swing.JTextField();
        txtPontuacaoPrimeiroLugar = new javax.swing.JTextField();
        pnlMedia = new javax.swing.JPanel();
        lblQtdMembrosNoRanking1 = new javax.swing.JLabel();
        txtMediaDePontuacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ranking das atividades");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTopo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ranking");

        javax.swing.GroupLayout pnlTopoLayout = new javax.swing.GroupLayout(pnlTopo);
        pnlTopo.setLayout(pnlTopoLayout);
        pnlTopoLayout.setHorizontalGroup(
            pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pnlTopoLayout.setVerticalGroup(
            pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlControles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Cancel.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar no ranking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        tabPanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtBuscarPorNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBuscarPorNome.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscarPorNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarPorNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnBuscarPorNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Zoom.png"))); // NOI18N
        btnBuscarPorNome.setText("Buscar");
        btnBuscarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarPorNomeLayout = new javax.swing.GroupLayout(pnlBuscarPorNome);
        pnlBuscarPorNome.setLayout(pnlBuscarPorNomeLayout);
        pnlBuscarPorNomeLayout.setHorizontalGroup(
            pnlBuscarPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPorNomeLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txtBuscarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBuscarPorNomeLayout.setVerticalGroup(
            pnlBuscarPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPorNomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlBuscarPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorNome))
                .addContainerGap())
        );

        tabPanelBuscar.addTab("Pelo nome do Membro", pnlBuscarPorNome);

        tbRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID Membro", "Membro", "Pontuação", "Data de realização da atividade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRanking.setShowGrid(true);
        jScrollPane2.setViewportView(tbRanking);
        if (tbRanking.getColumnModel().getColumnCount() > 0) {
            tbRanking.getColumnModel().getColumn(0).setMinWidth(65);
            tbRanking.getColumnModel().getColumn(0).setPreferredWidth(65);
            tbRanking.getColumnModel().getColumn(0).setMaxWidth(60);
            tbRanking.getColumnModel().getColumn(1).setMaxWidth(90);
            tbRanking.getColumnModel().getColumn(2).setMinWidth(200);
        }

        pnlMelhorColocados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPontuacaoSegundoLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPontuacaoSegundoLugar.setForeground(new java.awt.Color(255, 255, 255));
        txtPontuacaoSegundoLugar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontuacaoSegundoLugar.setText("0,0");
        txtPontuacaoSegundoLugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPontuacaoSegundoLugar.setEnabled(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24x24/Favourites.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24x24/Medium rating.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/24x24/Low rating.png"))); // NOI18N

        lblPrimeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrimeiro.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        lblPrimeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrimeiro.setText("1º");

        lblSegundo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSegundo.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblSegundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSegundo.setText("2º");

        lblTerceiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTerceiro.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblTerceiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTerceiro.setText("3º");

        lblPrimeiroLugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrimeiroLugar.setText("Primeiro lugar");

        lblSegundoLugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSegundoLugar.setText("Segundo lugar");

        lblTerceiroLugar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTerceiroLugar.setText("Terceiro lugar");

        lblPontuacaoPrimeiroLugar.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblPontuacaoPrimeiroLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontuacaoPrimeiroLugar.setText("Pontuação");

        lblPontuacaoTerceiroLugar.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblPontuacaoTerceiroLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontuacaoTerceiroLugar.setText("Pontuação");

        lblPontuacaoSegundoLugar.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblPontuacaoSegundoLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontuacaoSegundoLugar.setText("Pontuação");

        txtPontuacaoTerceiroLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPontuacaoTerceiroLugar.setForeground(new java.awt.Color(255, 255, 255));
        txtPontuacaoTerceiroLugar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontuacaoTerceiroLugar.setText("0,0");
        txtPontuacaoTerceiroLugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPontuacaoTerceiroLugar.setEnabled(false);

        txtPontuacaoPrimeiroLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPontuacaoPrimeiroLugar.setForeground(new java.awt.Color(255, 255, 255));
        txtPontuacaoPrimeiroLugar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontuacaoPrimeiroLugar.setText("0,0");
        txtPontuacaoPrimeiroLugar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPontuacaoPrimeiroLugar.setEnabled(false);

        pnlMedia.setBorder(javax.swing.BorderFactory.createTitledBorder("Média geral"));

        lblQtdMembrosNoRanking1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblQtdMembrosNoRanking1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdMembrosNoRanking1.setText("Pontuação média");

        txtMediaDePontuacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMediaDePontuacao.setForeground(new java.awt.Color(255, 255, 255));
        txtMediaDePontuacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMediaDePontuacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMediaDePontuacao.setEnabled(false);

        javax.swing.GroupLayout pnlMediaLayout = new javax.swing.GroupLayout(pnlMedia);
        pnlMedia.setLayout(pnlMediaLayout);
        pnlMediaLayout.setHorizontalGroup(
            pnlMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMediaLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnlMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQtdMembrosNoRanking1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMediaDePontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        pnlMediaLayout.setVerticalGroup(
            pnlMediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMediaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblQtdMembrosNoRanking1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMediaDePontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMelhoresDoRankingLayout = new javax.swing.GroupLayout(pnlMelhoresDoRanking);
        pnlMelhoresDoRanking.setLayout(pnlMelhoresDoRankingLayout);
        pnlMelhoresDoRankingLayout.setHorizontalGroup(
            pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                        .addComponent(lblPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrimeiroLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPontuacaoPrimeiroLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPontuacaoPrimeiroLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                        .addComponent(lblSegundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSegundoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPontuacaoSegundoLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPontuacaoSegundoLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                        .addComponent(lblTerceiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTerceiroLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPontuacaoTerceiroLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPontuacaoTerceiroLugar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(pnlMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMelhoresDoRankingLayout.setVerticalGroup(
            pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMelhoresDoRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                        .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPrimeiroLugar))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontuacaoPrimeiroLugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPontuacaoPrimeiroLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMelhoresDoRankingLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSegundoLugar))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTerceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTerceiroLugar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPontuacaoSegundoLugar)
                            .addComponent(lblPontuacaoTerceiroLugar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMelhoresDoRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPontuacaoSegundoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPontuacaoTerceiroLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedia.getAccessibleContext().setAccessibleName("");

        pnlMelhorColocados.addTab("Melhores colocados", new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Favourites.png")), pnlMelhoresDoRanking); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(pnlMelhorColocados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMelhorColocados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanelBuscar.getAccessibleContext().setAccessibleName("Por Nome");
        pnlMelhorColocados.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        usuario = Sessao.getUsuarioLogado();
        carregarDadosDeRanking();
    }//GEN-LAST:event_formWindowOpened

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnBuscarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorNomeActionPerformed
        if (!txtBuscarPorNome.getText().isBlank()) {
            realizarBuscaDeCadastroPorNome();
        } else {
            txtBuscarPorNome.setText("");
            JOptionPane.showMessageDialog(rootPane, "Digite o nome do membro para realizar a busca!", "Campo de busca vazio", JOptionPane.WARNING_MESSAGE);
            carregarDadosDeRanking();
        }
    }//GEN-LAST:event_btnBuscarPorNomeActionPerformed

    private void realizarBuscaDeCadastroPorNome() {
        List<Avaliacao> avaliacoes;
        try {
            avaliacoes = new AvaliacaoDAO().buscarPorNome(txtBuscarPorNome.getText());

            if (avaliacoes.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "A busca não retornou nenhum resultado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                calcularRanking(avaliacoes);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            exibeMensagemErroAoBuscar(ex);
        }
    }

    public void carregarDadosDeRanking() {
        List<Avaliacao> avaliacoes = null;
        try {
            avaliacoes = new AvaliacaoDAO().buscarTodos();

            if (avaliacoes.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "O ranking não pôde ser gerado porque nenhuma avaliação foi registrada.", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                calcularRanking(avaliacoes);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            exibeMensagemErroAoBuscar(ex);
        }
    }

    private void calcularRanking(List<Avaliacao> avaliacoes) {
        try {
            List<Ranking> ranking = new GeraRanking().gerarRanking(avaliacoes);
            preencherTabela(ranking);
        } catch (SQLException | ClassNotFoundException ex) {
           exibeMensagemErroAoBuscar(ex);
        }
    }

    private void preencherTabela(List<Ranking> rankings) throws SQLException, ClassNotFoundException {
        DefaultTableModel tabela = (DefaultTableModel) tbRanking.getModel();

        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }

        int posicaoRanking = 1;
        int acumulaMedia = 0;

        for (Ranking rnk : rankings) {
            String nomeMembro = String.format("%s %s", rnk.getMembro().getNome(), rnk.getMembro().getSobrenome());
            double media = rnk.getMedia();

            String[] linha = {
                    String.valueOf(posicaoRanking),
                    String.valueOf(rnk.getMembro().getId()),
                    nomeMembro,
                    String.format("%.1f", media),
                    FormataData.formataDataParaExibicao(rnk.getAtividade().getDataAtividade())
            };
            tabela.addRow(linha);

            exibirMelhorColocados(rnk, media, posicaoRanking, nomeMembro);
            acumulaMedia += (int) media;

            posicaoRanking++;
        }

        calcularMediaGeral(acumulaMedia, posicaoRanking - 1);

        centralizarConteudosDaTabela();
    }

    private void calcularMediaGeral(double acumulaMedia, int posicaoRanking) {
        if (posicaoRanking >= 2) {
            double mediaGeral = acumulaMedia / posicaoRanking;
            txtMediaDePontuacao.setText(String.format("%.1f", mediaGeral));
        } else {
            txtMediaDePontuacao.setText("0,0");
        }
    }

    private void exibirMelhorColocados(Ranking rnk, double media, int posicaoRanking, String nomeMembro) {
        if (media > 0) {
            if (posicaoRanking == 1) {
                lblPrimeiroLugar.setText(nomeMembro);
                txtPontuacaoPrimeiroLugar.setText(String.format("%.1f", rnk.getMedia()));
            } else if (posicaoRanking == 2) {
                lblSegundoLugar.setText(nomeMembro);
                txtPontuacaoSegundoLugar.setText(String.format("%.1f", rnk.getMedia()));
            } else if (posicaoRanking == 3) {
                lblTerceiroLugar.setText(nomeMembro);
                txtPontuacaoTerceiroLugar.setText(String.format("%.1f", rnk.getMedia()));
            }
        }
    }

    private void centralizarConteudosDaTabela() {
        DefaultTableCellRenderer cetralizarConteudo = new DefaultTableCellRenderer();
        cetralizarConteudo.setHorizontalAlignment(SwingConstants.CENTER);
        tbRanking.getColumnModel().getColumn(0).setCellRenderer(cetralizarConteudo);
        tbRanking.getColumnModel().getColumn(1).setCellRenderer(cetralizarConteudo);
        tbRanking.getColumnModel().getColumn(2).setCellRenderer(cetralizarConteudo);
        tbRanking.getColumnModel().getColumn(3).setCellRenderer(cetralizarConteudo);
        tbRanking.getColumnModel().getColumn(4).setCellRenderer(cetralizarConteudo);
    }

    private void exibeMensagemErroAoBuscar(Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar buscar o dado na base.\n" + ex.getMessage(), "Ocorreu um erro", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewRanking dialog = new ViewRanking(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorNome;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPontuacaoPrimeiroLugar;
    private javax.swing.JLabel lblPontuacaoSegundoLugar;
    private javax.swing.JLabel lblPontuacaoTerceiroLugar;
    private javax.swing.JLabel lblPrimeiro;
    private javax.swing.JLabel lblPrimeiroLugar;
    private javax.swing.JLabel lblQtdMembrosNoRanking1;
    private javax.swing.JLabel lblSegundo;
    private javax.swing.JLabel lblSegundoLugar;
    private javax.swing.JLabel lblTerceiro;
    private javax.swing.JLabel lblTerceiroLugar;
    private javax.swing.JPanel pnlBuscarPorNome;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlMedia;
    private javax.swing.JTabbedPane pnlMelhorColocados;
    private javax.swing.JPanel pnlMelhoresDoRanking;
    private javax.swing.JPanel pnlTopo;
    private javax.swing.JTabbedPane tabPanelBuscar;
    private javax.swing.JTable tbRanking;
    private javax.swing.JTextField txtBuscarPorNome;
    private javax.swing.JTextField txtMediaDePontuacao;
    private javax.swing.JTextField txtPontuacaoPrimeiroLugar;
    private javax.swing.JTextField txtPontuacaoSegundoLugar;
    private javax.swing.JTextField txtPontuacaoTerceiroLugar;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario;
}
