/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.vianna.sistemaclube.view.principal;

import br.edu.vianna.sistemaclube.dao.impl.*;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.AdministradorDAO;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.InstrutorDAO;
import br.edu.vianna.sistemaclube.dao.impl.usuariodao.MembroDAO;
import br.edu.vianna.sistemaclube.model.Clube;
import br.edu.vianna.sistemaclube.model.usuarios.Administrador;
import br.edu.vianna.sistemaclube.model.usuarios.Instrutor;
import br.edu.vianna.sistemaclube.model.usuarios.Membro;
import br.edu.vianna.sistemaclube.model.usuarios.Usuario;
import br.edu.vianna.sistemaclube.utils.datahora.FormataDataHora;
import br.edu.vianna.sistemaclube.utils.login.Sessao;
import br.edu.vianna.sistemaclube.view.cadastros.eventos.ViewDetalhesEventos;
import br.edu.vianna.sistemaclube.view.cadastros.eventos.ViewListarEventos;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesAdministradores;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesInstrutores;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.detalhescadastros.ViewDetalhesMembros;
import br.edu.vianna.sistemaclube.view.visualizacao.avaliacoes.ViewAvaliacaoAtividades;
import br.edu.vianna.sistemaclube.view.cadastros.atividades.ViewCadastroAtividades;
import br.edu.vianna.sistemaclube.view.cadastros.atividades.ViewDetalhesAtividades;
import br.edu.vianna.sistemaclube.view.cadastros.eventos.ViewCadastroEventos;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.ViewCadastroAdministrador;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.ViewCadastroInstrutor;
import br.edu.vianna.sistemaclube.view.cadastros.usuarios.ViewCadastroMembro;
import br.edu.vianna.sistemaclube.view.visualizacao.inscricoes.ViewInscreverEmAtividade;
import br.edu.vianna.sistemaclube.view.visualizacao.rankings.ViewRanking;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.SQLException;

import javax.swing.*;
import java.time.LocalDateTime;

/**
 * @author William
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlDadosUsuario = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        lblDataHoraLogin = new javax.swing.JLabel();
        lblLegendaId = new javax.swing.JLabel();
        LblLegendaUsuario = new javax.swing.JLabel();
        lblLegendaDataHoraLogin = new javax.swing.JLabel();
        pnlAuxiliar = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUltimosEventos = new javax.swing.JList<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUltimasAtividades = new javax.swing.JList<>();
        lblSaudacao1 = new javax.swing.JLabel();
        lblNomeUsuarioSaudacao = new javax.swing.JLabel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuArqTrocarUsuario = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        mnuArqSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadAdministrador = new javax.swing.JMenu();
        mnuCadastrarAdministrador = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuVisualizarDetalhesAdmin = new javax.swing.JMenuItem();
        separadorCad1 = new javax.swing.JPopupMenu.Separator();
        mnuCadInstrutor = new javax.swing.JMenu();
        mnuCadastrarInstrutor = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnuVisualizarDetalhesInstrutor = new javax.swing.JMenuItem();
        separadorCad2 = new javax.swing.JPopupMenu.Separator();
        mnuCadMembro = new javax.swing.JMenu();
        mnuCadastrarMembro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuVisualizarDetalhesMembro = new javax.swing.JMenuItem();
        separadorCad3 = new javax.swing.JPopupMenu.Separator();
        mnuCadEventos = new javax.swing.JMenu();
        mnuCadastrarEvento = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuVisualizarDetalhesEventos = new javax.swing.JMenuItem();
        separadorCad4 = new javax.swing.JPopupMenu.Separator();
        mnuCadAtividades = new javax.swing.JMenu();
        mnuCadastrarAtividade = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuVisualizarAtividadesCadastradas = new javax.swing.JMenuItem();
        mnuFinanceiro = new javax.swing.JMenu();
        mnuFinDashboard = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mnuFinCadastrarReceita = new javax.swing.JMenuItem();
        mnuFinCadastarDespesa = new javax.swing.JMenuItem();
        mnuEventos = new javax.swing.JMenu();
        mnuEvtListarEventos = new javax.swing.JMenuItem();
        mnuAtividades = new javax.swing.JMenu();
        mnuAtvVisualizarAtividades = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        mnuAtvAvaliarMembros = new javax.swing.JMenuItem();
        separadorRankAtiv = new javax.swing.JPopupMenu.Separator();
        mnuAtvRanking = new javax.swing.JMenuItem();
        mnuAvaliacoes = new javax.swing.JMenu();
        mnuAvlMembroVisualizarAvaliacoes = new javax.swing.JMenuItem();
        separadorAvl = new javax.swing.JPopupMenu.Separator();
        mnuAvlInstVisualizarAvaliacoes = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuAjdSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema MeuClube - beta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("viewPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MeuClubeLogo.png"))); // NOI18N
        lblLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblLogo.setOpaque(true);

        pnlDadosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"))); // NOI18N

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeUsuario.setText("Usuário");

        lblIdUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblIdUsuario.setText("000");

        lblDataHoraLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataHoraLogin.setText("01/01/00 00:00");

        lblLegendaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLegendaId.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblLegendaId.setText("ID");

        LblLegendaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LblLegendaUsuario.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        LblLegendaUsuario.setText("Usuário");

        lblLegendaDataHoraLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLegendaDataHoraLogin.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblLegendaDataHoraLogin.setText("Data/Hora Login");

        javax.swing.GroupLayout pnlDadosUsuarioLayout = new javax.swing.GroupLayout(pnlDadosUsuario);
        pnlDadosUsuario.setLayout(pnlDadosUsuarioLayout);
        pnlDadosUsuarioLayout.setHorizontalGroup(
            pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLegendaId)
                    .addComponent(lblLegendaDataHoraLogin)
                    .addComponent(lblDataHoraLogin)
                    .addComponent(LblLegendaUsuario)
                    .addComponent(lblIdUsuario)
                    .addComponent(lblNomeUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosUsuarioLayout.setVerticalGroup(
            pnlDadosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosUsuarioLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblLegendaId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblLegendaUsuario)
                .addGap(2, 2, 2)
                .addComponent(lblNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblLegendaDataHoraLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataHoraLogin)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogo)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlAuxiliar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lstUltimosEventos.setToolTipText("Recurso não implementado!");
        jScrollPane1.setViewportView(lstUltimosEventos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Próximos eventos", new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Calendar.png")), jPanel1); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lstUltimasAtividades.setToolTipText("Recurso não implementado!");
        jScrollPane2.setViewportView(lstUltimasAtividades);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Últimas atividades", new javax.swing.ImageIcon(getClass().getResource("/img/16x16/New.png")), jPanel2); // NOI18N

        lblSaudacao1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblSaudacao1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        lblSaudacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaudacao1.setText("Bem-vindo ao sistema,");
        lblSaudacao1.setToolTipText("");

        lblNomeUsuarioSaudacao.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNomeUsuarioSaudacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeUsuarioSaudacao.setText("Usuário");

        javax.swing.GroupLayout pnlAuxiliarLayout = new javax.swing.GroupLayout(pnlAuxiliar);
        pnlAuxiliar.setLayout(pnlAuxiliarLayout);
        pnlAuxiliarLayout.setHorizontalGroup(
            pnlAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuxiliarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeUsuarioSaudacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSaudacao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlAuxiliarLayout.setVerticalGroup(
            pnlAuxiliarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAuxiliarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblSaudacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuarioSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mnuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/archive.png"))); // NOI18N
        mnuArquivo.setText("Arquivo");
        mnuArquivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuArqTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Person.png"))); // NOI18N
        mnuArqTrocarUsuario.setText("Trocar usuário");
        mnuArqTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArqTrocarUsuarioActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuArqTrocarUsuario);
        mnuArquivo.add(jSeparator15);

        mnuArqSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Exit.png"))); // NOI18N
        mnuArqSair.setText("Sair");
        mnuArqSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArqSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuArqSair);

        mnuPrincipal.add(mnuArquivo);

        mnuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/user.png"))); // NOI18N
        mnuCadastros.setText("Cadastros");
        mnuCadastros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuCadAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Boss.png"))); // NOI18N
        mnuCadAdministrador.setText("Administrador");

        mnuCadastrarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuCadastrarAdministrador.setText("Cadastrar");
        mnuCadastrarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarAdministradorActionPerformed(evt);
            }
        });
        mnuCadAdministrador.add(mnuCadastrarAdministrador);
        mnuCadAdministrador.add(jSeparator10);

        mnuVisualizarDetalhesAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuVisualizarDetalhesAdmin.setText("Visualizar administradores cadastrados");
        mnuVisualizarDetalhesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisualizarDetalhesAdminActionPerformed(evt);
            }
        });
        mnuCadAdministrador.add(mnuVisualizarDetalhesAdmin);

        mnuCadastros.add(mnuCadAdministrador);
        mnuCadastros.add(separadorCad1);

        mnuCadInstrutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Female.png"))); // NOI18N
        mnuCadInstrutor.setText("Instrutor");

        mnuCadastrarInstrutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuCadastrarInstrutor.setText("Cadastrar");
        mnuCadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarInstrutorActionPerformed(evt);
            }
        });
        mnuCadInstrutor.add(mnuCadastrarInstrutor);
        mnuCadInstrutor.add(jSeparator9);

        mnuVisualizarDetalhesInstrutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuVisualizarDetalhesInstrutor.setText("Visualizar instrutores cadastrados");
        mnuVisualizarDetalhesInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisualizarDetalhesInstrutorActionPerformed(evt);
            }
        });
        mnuCadInstrutor.add(mnuVisualizarDetalhesInstrutor);

        mnuCadastros.add(mnuCadInstrutor);
        mnuCadastros.add(separadorCad2);

        mnuCadMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Male.png"))); // NOI18N
        mnuCadMembro.setText("Membro");

        mnuCadastrarMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuCadastrarMembro.setText("Cadastrar");
        mnuCadastrarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarMembroActionPerformed(evt);
            }
        });
        mnuCadMembro.add(mnuCadastrarMembro);
        mnuCadMembro.add(jSeparator1);

        mnuVisualizarDetalhesMembro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuVisualizarDetalhesMembro.setText("Visualizar membros cadastrados");
        mnuVisualizarDetalhesMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisualizarDetalhesMembroActionPerformed(evt);
            }
        });
        mnuCadMembro.add(mnuVisualizarDetalhesMembro);

        mnuCadastros.add(mnuCadMembro);
        mnuCadastros.add(separadorCad3);

        mnuCadEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Calendar.png"))); // NOI18N
        mnuCadEventos.setText("Eventos");

        mnuCadastrarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuCadastrarEvento.setText("Cadastrar evento");
        mnuCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarEventoActionPerformed(evt);
            }
        });
        mnuCadEventos.add(mnuCadastrarEvento);
        mnuCadEventos.add(jSeparator8);

        mnuVisualizarDetalhesEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuVisualizarDetalhesEventos.setText("Visualizar detalhes de eventos");
        mnuVisualizarDetalhesEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisualizarDetalhesEventosActionPerformed(evt);
            }
        });
        mnuCadEventos.add(mnuVisualizarDetalhesEventos);

        mnuCadastros.add(mnuCadEventos);
        mnuCadastros.add(separadorCad4);

        mnuCadAtividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Table.png"))); // NOI18N
        mnuCadAtividades.setText("Atividades");

        mnuCadastrarAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuCadastrarAtividade.setText("Cadastrar atividade");
        mnuCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarAtividadeActionPerformed(evt);
            }
        });
        mnuCadAtividades.add(mnuCadastrarAtividade);
        mnuCadAtividades.add(jSeparator7);

        mnuVisualizarAtividadesCadastradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Table.png"))); // NOI18N
        mnuVisualizarAtividadesCadastradas.setText("Visualizar atividades cadastradas");
        mnuVisualizarAtividadesCadastradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVisualizarAtividadesCadastradasActionPerformed(evt);
            }
        });
        mnuCadAtividades.add(mnuVisualizarAtividadesCadastradas);

        mnuCadastros.add(mnuCadAtividades);

        mnuPrincipal.add(mnuCadastros);

        mnuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/dollar-sign.png"))); // NOI18N
        mnuFinanceiro.setText("Financeiro");
        mnuFinanceiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuFinDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Report.png"))); // NOI18N
        mnuFinDashboard.setText("Dashboard");
        mnuFinDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinDashboardActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuFinDashboard);
        mnuFinanceiro.add(jSeparator11);

        mnuFinCadastrarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Create.png"))); // NOI18N
        mnuFinCadastrarReceita.setText("Cadastrar receita");
        mnuFinCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinCadastrarReceitaActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuFinCadastrarReceita);

        mnuFinCadastarDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/No-entry.png"))); // NOI18N
        mnuFinCadastarDespesa.setText("Cadastrar despesa");
        mnuFinCadastarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFinCadastarDespesaActionPerformed(evt);
            }
        });
        mnuFinanceiro.add(mnuFinCadastarDespesa);

        mnuPrincipal.add(mnuFinanceiro);

        mnuEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/calendar.png"))); // NOI18N
        mnuEventos.setText("Eventos");
        mnuEventos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuEvtListarEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuEvtListarEventos.setText("Listar eventos");
        mnuEvtListarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEvtListarEventosActionPerformed(evt);
            }
        });
        mnuEventos.add(mnuEvtListarEventos);

        mnuPrincipal.add(mnuEventos);

        mnuAtividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/activity.png"))); // NOI18N
        mnuAtividades.setText("Atividades");
        mnuAtividades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuAtvVisualizarAtividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/List.png"))); // NOI18N
        mnuAtvVisualizarAtividades.setLabel("Atividades disponíveis para inscrição");
        mnuAtvVisualizarAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtvVisualizarAtividadesActionPerformed(evt);
            }
        });
        mnuAtividades.add(mnuAtvVisualizarAtividades);
        mnuAtividades.add(jSeparator13);

        mnuAtvAvaliarMembros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnuAtvAvaliarMembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Yes.png"))); // NOI18N
        mnuAtvAvaliarMembros.setText("Avaliar atividades");
        mnuAtvAvaliarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtvAvaliarMembrosActionPerformed(evt);
            }
        });
        mnuAtividades.add(mnuAtvAvaliarMembros);
        mnuAtividades.add(separadorRankAtiv);

        mnuAtvRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/3d bar chart.png"))); // NOI18N
        mnuAtvRanking.setText("Visualizar o Ranking");
        mnuAtvRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtvRankingActionPerformed(evt);
            }
        });
        mnuAtividades.add(mnuAtvRanking);

        mnuPrincipal.add(mnuAtividades);

        mnuAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/award.png"))); // NOI18N
        mnuAvaliacoes.setText("Avaliações");
        mnuAvaliacoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuAvlMembroVisualizarAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Yes.png"))); // NOI18N
        mnuAvlMembroVisualizarAvaliacoes.setText("Visualizar minhas avaliações");
        mnuAvlMembroVisualizarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAvlMembroVisualizarAvaliacoesActionPerformed(evt);
            }
        });
        mnuAvaliacoes.add(mnuAvlMembroVisualizarAvaliacoes);
        mnuAvaliacoes.add(separadorAvl);

        mnuAvlInstVisualizarAvaliacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Apply.png"))); // NOI18N
        mnuAvlInstVisualizarAvaliacoes.setText("Visualizar avaliações");
        mnuAvlInstVisualizarAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAvlInstVisualizarAvaliacoesActionPerformed(evt);
            }
        });
        mnuAvaliacoes.add(mnuAvlInstVisualizarAvaliacoes);

        mnuPrincipal.add(mnuAvaliacoes);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16_monocrom/help-circle.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuAjdSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/16x16/Info.png"))); // NOI18N
        mnuAjdSobre.setText("Sobre");
        mnuAjdSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAjdSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuAjdSobre);

        mnuPrincipal.add(mnuAjuda);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAuxiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        definirVisualizacaoDeMenus();
        //AS FUNÇÕES ABAIXO NÃO ESTÃO SENDO UTILIZADAS NESTA VERSÃO.
        //espelharListasComABase();
        //popularListasMembros();
    }//GEN-LAST:event_formWindowOpened

    private void mnuArqSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArqSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuArqSairActionPerformed

    private void mnuArqTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArqTrocarUsuarioActionPerformed
        trocarUsuario();
    }//GEN-LAST:event_mnuArqTrocarUsuarioActionPerformed

    private void mnuCadastrarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarAdministradorActionPerformed
        ViewCadastroAdministrador viewCadAdmin = new ViewCadastroAdministrador(this, true);
        viewCadAdmin.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarAdministradorActionPerformed

    private void mnuCadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarInstrutorActionPerformed
        ViewCadastroInstrutor viewCadInstrutor = new ViewCadastroInstrutor(this, true);
        viewCadInstrutor.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarInstrutorActionPerformed

    private void mnuCadastrarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarMembroActionPerformed
        ViewCadastroMembro viewCadMembro = new ViewCadastroMembro(this, true);
        viewCadMembro.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarMembroActionPerformed

    private void mnuCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarEventoActionPerformed
        ViewCadastroEventos viewCadEventos = new ViewCadastroEventos(this, true);
        viewCadEventos.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarEventoActionPerformed

    private void mnuCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarAtividadeActionPerformed
        ViewCadastroAtividades viewCadAtividades = new ViewCadastroAtividades(this, true);
        viewCadAtividades.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarAtividadeActionPerformed

    private void mnuAtvVisualizarAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtvVisualizarAtividadesActionPerformed
        ViewInscreverEmAtividade viewInscreverEmAtividade = new ViewInscreverEmAtividade(this, true);
        viewInscreverEmAtividade.setVisible(true);
    }//GEN-LAST:event_mnuAtvVisualizarAtividadesActionPerformed

    private void mnuAtvAvaliarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtvAvaliarMembrosActionPerformed
        ViewAvaliacaoAtividades viewAvaliacaoMembros = new ViewAvaliacaoAtividades(this, true);
        viewAvaliacaoMembros.setVisible(true);
    }//GEN-LAST:event_mnuAtvAvaliarMembrosActionPerformed

    private void mnuAtvRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtvRankingActionPerformed
        ViewRanking viewRankings = new ViewRanking(this, true);
        viewRankings.setVisible(true);
    }//GEN-LAST:event_mnuAtvRankingActionPerformed

    private void mnuFinDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinDashboardActionPerformed
        recursoNaoImplementado();
    }//GEN-LAST:event_mnuFinDashboardActionPerformed

    private void mnuFinCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinCadastrarReceitaActionPerformed
        recursoNaoImplementado();
    }//GEN-LAST:event_mnuFinCadastrarReceitaActionPerformed

    private void mnuFinCadastarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFinCadastarDespesaActionPerformed
        recursoNaoImplementado();
    }//GEN-LAST:event_mnuFinCadastarDespesaActionPerformed

    private void mnuEvtListarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEvtListarEventosActionPerformed
        ViewListarEventos viewInfoEventos = new ViewListarEventos(this, true);
        viewInfoEventos.setVisible(true);
    }//GEN-LAST:event_mnuEvtListarEventosActionPerformed

    private void mnuAvlMembroVisualizarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAvlMembroVisualizarAvaliacoesActionPerformed
        recursoNaoImplementado();
    }//GEN-LAST:event_mnuAvlMembroVisualizarAvaliacoesActionPerformed

    private void mnuAvlInstVisualizarAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAvlInstVisualizarAvaliacoesActionPerformed
        recursoNaoImplementado();
    }//GEN-LAST:event_mnuAvlInstVisualizarAvaliacoesActionPerformed

    private void mnuVisualizarDetalhesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisualizarDetalhesAdminActionPerformed
        ViewDetalhesAdministradores viewDetalhesAdministradores = new ViewDetalhesAdministradores(this, true);
        viewDetalhesAdministradores.setVisible(true);
    }//GEN-LAST:event_mnuVisualizarDetalhesAdminActionPerformed

    private void mnuVisualizarDetalhesInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisualizarDetalhesInstrutorActionPerformed
        ViewDetalhesInstrutores viewDetalhesInstrutores = new ViewDetalhesInstrutores(this, true);
        viewDetalhesInstrutores.setVisible(true);
    }//GEN-LAST:event_mnuVisualizarDetalhesInstrutorActionPerformed

    private void mnuVisualizarDetalhesMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisualizarDetalhesMembroActionPerformed
        ViewDetalhesMembros viewDetalhesMembros = new ViewDetalhesMembros(this, true);
        viewDetalhesMembros.setVisible(true);
    }//GEN-LAST:event_mnuVisualizarDetalhesMembroActionPerformed

    private void mnuVisualizarDetalhesEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisualizarDetalhesEventosActionPerformed
        ViewDetalhesEventos viewDetalhesEventos = new ViewDetalhesEventos(this, true);
        viewDetalhesEventos.setVisible(true);
    }//GEN-LAST:event_mnuVisualizarDetalhesEventosActionPerformed

    private void mnuVisualizarAtividadesCadastradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVisualizarAtividadesCadastradasActionPerformed
        ViewDetalhesAtividades viewDetalhesAtividades = new ViewDetalhesAtividades(this, true);
        viewDetalhesAtividades.setVisible(true);
    }//GEN-LAST:event_mnuVisualizarAtividadesCadastradasActionPerformed

    private void mnuAjdSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAjdSobreActionPerformed
        ViewSobre viewSobre = new ViewSobre(this, true);
        viewSobre.setVisible(true);
    }//GEN-LAST:event_mnuAjdSobreActionPerformed

    private void recursoNaoImplementado() {
        JOptionPane.showMessageDialog(rootPane, "Recurso ainda não implementado!", "Em desenvolvimento", JOptionPane.INFORMATION_MESSAGE);
    }

    private void trocarUsuario() {
        usuario = null;
        Sessao.setUsuarioLogado(null);
        definirVisualizacaoDeMenus();
    }

    private void popularListasNaViewPrincipal() {
        // Em desenvolvimento.
    }

    private void espelharListasComABase() {
        Clube clube = Clube.getInstance();
        try {
            clube.addAtividades(new AtividadeDAO().buscarTodos());
            clube.addEventos(new EventoDAO().buscarTodos());
            clube.addMembros(new MembroDAO().buscarTodos());
            clube.addInscricoesAtividades(new InscricaoAtividadeDAO().buscarTodos());
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar carregar dos dados da base. Contate o suporte.\nERRO: " + ex.getMessage(), "Ocorreu um erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popularListasMembros() {
        if (usuario instanceof Membro) {
            Membro membro = (Membro) usuario;
            int id = membro.getId();
            try {
                membro.addInscricoesAtividades(new InscricaoAtividadeDAO().buscarTodosPorIdMembro(id));
                membro.addAvaliacoes(new AvaliacaoDAO().buscarTodosPorIdMembro(id));
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar carregar dos dados da base. Contate o suporte.\nERRO: " + ex.getMessage(), "Ocorreu um erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void definirVisualizacaoDeMenus() {
        ViewLogin viewLogin = new ViewLogin(this, true);
        this.mnuCadastros.setVisible(false);
        this.mnuFinanceiro.setVisible(false);
        this.mnuEventos.setVisible(false);
        this.mnuAvaliacoes.setVisible(false);
        this.mnuAtividades.setVisible(false);
        // View Login.
        viewLogin.setVisible(true);

        usuario = Sessao.getUsuarioLogado();

        // Dados do usuário.
        exibirDadosUsuario();
        // Visibilidade de menus.
        estadoDeExibicaoDosMenus();
    }

    private void exibirDadosUsuario() {
        try {
            if (usuario instanceof Administrador) {
                Administrador admin = (Administrador) usuario;
                admin.setDataUltimoAcesso(LocalDateTime.now());
                new AdministradorDAO().atualizarDataUltimoAcesso(admin);
                //
                lblNomeUsuarioSaudacao.setText(admin.getNome());
                lblIdUsuario.setText(String.format("%d", admin.getId()));
                lblNomeUsuario.setText(String.format("%s %s", admin.getNome(), admin.getSobrenome()));
                lblDataHoraLogin.setText(FormataDataHora.formataDataHoraParaExibicaoSemSegundos(admin.getDataUltimoAcesso()));
            } else if (usuario instanceof Instrutor) {
                Instrutor instrutor = (Instrutor) usuario;
                instrutor.setDataUltimoAcesso(LocalDateTime.now());
                new InstrutorDAO().atualizarDataUltimoAcesso(instrutor);
                //
                lblNomeUsuarioSaudacao.setText(instrutor.getNome());
                lblIdUsuario.setText(String.format("%d", instrutor.getId()));
                lblNomeUsuario.setText(String.format("%s %s", instrutor.getNome(), instrutor.getSobrenome()));
                lblDataHoraLogin.setText(FormataDataHora.formataDataHoraParaExibicaoSemSegundos(instrutor.getDataUltimoAcesso()));
            } else if (usuario instanceof Membro) {
                Membro membro = (Membro) usuario;
                membro.setDataUltimoAcesso(LocalDateTime.now());
                new MembroDAO().atualizarDataUltimoAcesso(membro);
                //
                lblNomeUsuarioSaudacao.setText(membro.getNome());
                lblIdUsuario.setText(String.format("%d", membro.getId()));
                lblNomeUsuario.setText(String.format("%s %s", membro.getNome(), membro.getSobrenome()));
                lblDataHoraLogin.setText(FormataDataHora.formataDataHoraParaExibicaoSemSegundos(membro.getDataUltimoAcesso()));
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Ocorreu um erro ao tentar realizar a operação!\nERRO: " + ex.getMessage(), "Ocorreu um erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void estadoDeExibicaoDosMenus() {
        if (usuario instanceof Administrador) {
            mnuCadastros.setVisible(true);
            mnuCadAdministrador.setVisible(true);
            mnuCadInstrutor.setVisible(true);
            mnuCadMembro.setVisible(true);
            mnuCadEventos.setVisible(true);
            mnuCadAtividades.setVisible(true);
            separadorCad1.setVisible(true);
            separadorCad2.setVisible(true);
            separadorCad3.setVisible(true);
            separadorCad4.setVisible(true);
            mnuFinanceiro.setVisible(true);
            mnuEventos.setVisible(true);
            mnuAtividades.setVisible(true);
            separadorRankAtiv.setVisible(true);
            mnuAtvAvaliarMembros.setVisible(true);
            mnuAvaliacoes.setVisible(true);
            mnuAvlMembroVisualizarAvaliacoes.setVisible(false);
            separadorAvl.setVisible(false);
            mnuAvlInstVisualizarAvaliacoes.setVisible(true);
        } else if (usuario instanceof Instrutor) {
            //CADASTROS.
            mnuCadastros.setVisible(true);
            separadorCad1.setVisible(false);
            separadorCad2.setVisible(false);
            separadorCad3.setVisible(false);
            mnuFinanceiro.setVisible(false);
            mnuCadAdministrador.setVisible(false);
            mnuCadInstrutor.setVisible(false);
            mnuCadMembro.setVisible(false);
            mnuCadastrarEvento.setVisible(true);
            mnuCadAtividades.setVisible(true);
            mnuAtvAvaliarMembros.setVisible(true);
            mnuAvaliacoes.setVisible(true);
            separadorRankAtiv.setVisible(true);
            mnuAvlMembroVisualizarAvaliacoes.setVisible(false);
            separadorAvl.setVisible(true);
            mnuAvlInstVisualizarAvaliacoes.setVisible(true);
            //EVENTOS
            mnuEventos.setVisible(true);
            mnuAtividades.setVisible(true);
        } else if (usuario instanceof Membro) {
            mnuCadastros.setVisible(false);
            mnuFinanceiro.setVisible(false);
            mnuEventos.setVisible(true);
            mnuAtividades.setVisible(true);
            separadorRankAtiv.setVisible(false);
            mnuAtvAvaliarMembros.setVisible(false);
            mnuAvaliacoes.setVisible(true);
            mnuAvlMembroVisualizarAvaliacoes.setVisible(true);
            separadorAvl.setVisible(false);
            mnuAvlInstVisualizarAvaliacoes.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (Exception fallbackEx) {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception systemFallbackEx) {
                    java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, systemFallbackEx);
                }
            }
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblLegendaUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDataHoraLogin;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblLegendaDataHoraLogin;
    private javax.swing.JLabel lblLegendaId;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblNomeUsuarioSaudacao;
    private javax.swing.JLabel lblSaudacao1;
    private javax.swing.JList<String> lstUltimasAtividades;
    private javax.swing.JList<String> lstUltimosEventos;
    private javax.swing.JMenuItem mnuAjdSobre;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuArqSair;
    private javax.swing.JMenuItem mnuArqTrocarUsuario;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuAtividades;
    private javax.swing.JMenuItem mnuAtvAvaliarMembros;
    private javax.swing.JMenuItem mnuAtvRanking;
    private javax.swing.JMenuItem mnuAtvVisualizarAtividades;
    private javax.swing.JMenu mnuAvaliacoes;
    private javax.swing.JMenuItem mnuAvlInstVisualizarAvaliacoes;
    private javax.swing.JMenuItem mnuAvlMembroVisualizarAvaliacoes;
    private javax.swing.JMenu mnuCadAdministrador;
    private javax.swing.JMenu mnuCadAtividades;
    private javax.swing.JMenu mnuCadEventos;
    private javax.swing.JMenu mnuCadInstrutor;
    private javax.swing.JMenu mnuCadMembro;
    private javax.swing.JMenuItem mnuCadastrarAdministrador;
    private javax.swing.JMenuItem mnuCadastrarAtividade;
    private javax.swing.JMenuItem mnuCadastrarEvento;
    private javax.swing.JMenuItem mnuCadastrarInstrutor;
    private javax.swing.JMenuItem mnuCadastrarMembro;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuEventos;
    private javax.swing.JMenuItem mnuEvtListarEventos;
    private javax.swing.JMenuItem mnuFinCadastarDespesa;
    private javax.swing.JMenuItem mnuFinCadastrarReceita;
    private javax.swing.JMenuItem mnuFinDashboard;
    private javax.swing.JMenu mnuFinanceiro;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenuItem mnuVisualizarAtividadesCadastradas;
    private javax.swing.JMenuItem mnuVisualizarDetalhesAdmin;
    private javax.swing.JMenuItem mnuVisualizarDetalhesEventos;
    private javax.swing.JMenuItem mnuVisualizarDetalhesInstrutor;
    private javax.swing.JMenuItem mnuVisualizarDetalhesMembro;
    private javax.swing.JPanel pnlAuxiliar;
    private javax.swing.JPanel pnlDadosUsuario;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPopupMenu.Separator separadorAvl;
    private javax.swing.JPopupMenu.Separator separadorCad1;
    private javax.swing.JPopupMenu.Separator separadorCad2;
    private javax.swing.JPopupMenu.Separator separadorCad3;
    private javax.swing.JPopupMenu.Separator separadorCad4;
    private javax.swing.JPopupMenu.Separator separadorRankAtiv;
    // End of variables declaration//GEN-END:variables
    private Usuario usuario;
    private Clube clube;
}
